### ISSUE TITLE
Use collection install

### ISSUE THREAD

**Issue by fedejaure** [fedejaure/raspberry-pi-playbook#57]
## Use collection install

Use collection install in order to install the requirements:

`ansible-galaxy collection install -r requirements.yml`

example  `requirements.yml`:

```
---
roles:
  # Install a role from Ansible Galaxy.
  - name: geerlingguy.java
    version: 1.9.6

collections:
  # Install a collection from Ansible Galaxy.
  - name: geerlingguy.php_roles
    version: 0.9.3
    source: https://galaxy.ansible.com
```

https://docs.ansible.com/ansible/latest/user_guide/collections_using.html
